# Generated by Django 5.1.14 on 2026-07-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0088_alter_credentials_credential_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoJoinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_join_users', to='bots.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'email'), name='unique_project_auto_join_user_email')],
            },
        ),
    ]
