# Generated by Django 5.1.14 on 2026-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0089_autojoinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='autojoinuser',
            name='teams_webhook_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
